### PR TITLE
Fix keystone v3 creds format

### PR DESCRIPTION
**Pull request by mtatsuma**

### CODE REVIEW

**Comment by mtatsuma** [comment]
I found a bug in keystone v3 creds format. The correct format is documented in https://developer.openstack.org/api-ref/identity/v3/?expanded=password-authentication-with-unscoped-authorization-detail#password-authentication-with-unscoped-authorization

**Comment by Kami** [comment]
Good catch, thanks :+1: 

It would be great if you could also add a test case for it if you get a chance.

**Comment by mtatsuma** [comment]
Thank you for your comment. I added test code about this patch. Could you review it?

**Comment by Kami** [comment]
LGTM, thanks again for your contribution :+1: 

It will be included in the next stable release (v3.0.0).

**Comment by Kami** [comment]
EDIT: Ignore my comment above - forgot keystone auth backend is not installed by default.

You can install it yourself directly from git using pip - https://docs.stackstorm.com/authentication.html#auth-backends.

**Pull request merged**
